In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [5]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [7]:
df.dropna(inplace=True)

In [9]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [11]:
df['family'] = df['SibSp'] + df['Parch']

In [13]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [15]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
X_train.head()

      Age     Fare  SibSp  Parch  family
328  31.0  20.5250      1      1       2
73   26.0  14.4542      1      0       1
253  30.0  16.1000      1      0       1
719  33.0   7.7750      0      0       0
666  25.0  13.0000      0      0       0

In [21]:
# Without binarization

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6293706293706294

In [23]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

0.6527190923317685

In [25]:
# Applying Binarization
from sklearn.preprocessing import Binarizer

In [27]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [35]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [37]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family  Age  Fare
0       1.0  1.0   0.0
1       2.0  0.0   0.0
2       2.0  1.0   0.0
3       1.0  2.0   1.0
4       2.0  2.0   3.0
..      ...  ...   ...
778     3.0  3.0   1.0
779     1.0  2.0   1.0
780     0.0  2.0   1.0
781     0.0  2.0   0.0
782     2.0  0.0   0.0

[783 rows x 3 columns]

In [39]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.6717557251908397

In [41]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

0.6449267399267399